#!/usr/bin/env python3
from __future__ import annotations

import argparse
import fnmatch
import json
import re
import shutil
import sys
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tools" / "_vendor"))

import yaml


SCHEMA_DIR = ROOT / "schemas"
PROJECTS_ROOT = ROOT / "project_data" / "projects"
CANONICAL_TEXT_ROOTS = [ROOT / "AGENTS.md", ROOT / "docs", ROOT / ".agents"]
FORBIDDEN_CANONICAL_TOKENS = (".Codex", ".claude", "CLAUDE.md")
LEGACY_FILE_PATTERNS = (
    "project_data/series/**/*.yaml",
    "project_data/episodes/**/*.yaml",
    "project_data/series/*.yaml",
    "project_data/episodes/*.yaml",
)
COMPAT_NOTICE = (
    "<!-- compat mirror: generated by tools/workflow_guard.py sync-compat. "
    "Do not edit this file directly. -->\n\n"
)


@dataclass
class Issue:
    level: str
    message: str
    path: str | None = None


def rel(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def load_yaml(path: Path) -> Any:
    text = path.read_text()
    return yaml.safe_load(text) if text.strip() else None


def dump_yaml(data: Any) -> str:
    return yaml.safe_dump(data, sort_keys=False, allow_unicode=True)


def parse_version(value: str) -> tuple[int, ...]:
    match = re.search(r"-v(\d+(?:\.\d+)*)", value)
    if not match:
        return (0,)
    return tuple(int(part) for part in match.group(1).split("."))


def latest_file(patterns: list[str] | tuple[str, ...]) -> Path | None:
    candidates: list[Path] = []
    for pattern in patterns:
        candidates.extend(ROOT.glob(pattern))
    files = [path for path in candidates if path.is_file()]
    if not files:
        return None
    files.sort(key=lambda path: (parse_version(path.name), path.name))
    return files[-1]


def latest_formal_file(pattern: str) -> Path | None:
    return latest_file([pattern])


def project_pattern(project_id: str, relative_pattern: str) -> str:
    return f"project_data/projects/{project_id}/{relative_pattern}"


def latest_review(
    project_id: str,
    stage: str,
    review_type: str,
    episode_id: str | None = None,
    phase: str | None = None,
) -> dict[str, Any] | None:
    if review_type == "business":
        patterns = [
            project_pattern(project_id, "series/reviews/business/business-review-report-*.yaml"),
            project_pattern(project_id, "episodes/*/reviews/business/business-review-report-*.yaml"),
        ]
    else:
        patterns = [
            project_pattern(project_id, "series/reviews/compliance/compliance-report-*.yaml"),
            project_pattern(project_id, "episodes/*/reviews/compliance/compliance-report-*.yaml"),
        ]

    matches: list[tuple[tuple[int, ...], dict[str, Any]]] = []
    for pattern in patterns:
        for path in ROOT.glob(pattern):
            if not path.is_file():
                continue
            payload = load_yaml(path) or {}
            metadata = payload.get("metadata", {})
            if metadata.get("target_stage") != stage:
                continue
            if episode_id is None:
                if metadata.get("episode_id") not in ("", None):
                    continue
            elif metadata.get("episode_id") != episode_id:
                continue
            if phase is not None and metadata.get("target_review_phase") != phase:
                continue
            matches.append((parse_version(path.name), {"path": rel(path), "data": payload}))
    if not matches:
        return None
    matches.sort(key=lambda item: item[0])
    return matches[-1][1]


def review_verdict(review: dict[str, Any] | None) -> str:
    if not review:
        return "missing"
    return review["data"].get("conclusion", {}).get("verdict", "missing")


def review_gate(review: dict[str, Any] | None) -> str:
    if not review:
        return "missing"
    return review["data"].get("conclusion", {}).get("gate_decision", "missing")


def business_allows(verdict: str) -> bool:
    return verdict in {"pass", "pass_with_revisions"}


def compliance_allows(verdict: str) -> bool:
    return verdict in {"pass", "conditional_pass"}


def get_nested(mapping: Any, path: str) -> Any:
    current = mapping
    for token in path.split("."):
        if not isinstance(current, dict) or token not in current:
            return None
        current = current[token]
    return current


def path_exists_in_schema(schema: dict[str, Any], dotted_path: str) -> bool:
    node = schema
    for token in dotted_path.split("."):
        if token.endswith("[]"):
            token = token[:-2]
            props = node.get("properties", {})
            if token not in props:
                return False
            node = props[token]
            if node.get("type") != "array":
                return False
            node = node.get("items", {})
        else:
            props = node.get("properties", {})
            if token not in props:
                return False
            node = props[token]
    return True


def validate_json_schema(instance: Any, schema: dict[str, Any], location: str = "$") -> list[Issue]:
    issues: list[Issue] = []
    schema_type = schema.get("type")
    if "enum" in schema and instance not in schema["enum"]:
        issues.append(Issue("error", f"{location}: expected one of {schema['enum']}, got {instance!r}"))
        return issues
    if schema_type == "object":
        if not isinstance(instance, dict):
            issues.append(Issue("error", f"{location}: expected object"))
            return issues
        required = schema.get("required", [])
        for key in required:
            if key not in instance:
                issues.append(Issue("error", f"{location}: missing required key `{key}`"))
        props = schema.get("properties", {})
        if schema.get("additionalProperties") is False:
            for key in instance:
                if key not in props:
                    issues.append(Issue("error", f"{location}: unexpected key `{key}`"))
        for key, value in instance.items():
            if key in props:
                issues.extend(validate_json_schema(value, props[key], f"{location}.{key}"))
    elif schema_type == "array":
        if not isinstance(instance, list):
            issues.append(Issue("error", f"{location}: expected array"))
            return issues
        if "minItems" in schema and len(instance) < schema["minItems"]:
            issues.append(Issue("error", f"{location}: expected at least {schema['minItems']} items"))
        item_schema = schema.get("items")
        if item_schema:
            for index, item in enumerate(instance):
                issues.extend(validate_json_schema(item, item_schema, f"{location}[{index}]"))
    elif schema_type == "string":
        if not isinstance(instance, str):
            issues.append(Issue("error", f"{location}: expected string"))
    elif schema_type == "integer":
        if not isinstance(instance, int) or isinstance(instance, bool):
            issues.append(Issue("error", f"{location}: expected integer"))
    elif schema_type == "boolean":
        if not isinstance(instance, bool):
            issues.append(Issue("error", f"{location}: expected boolean"))
    elif schema_type == "number":
        if not isinstance(instance, (int, float)) or isinstance(instance, bool):
            issues.append(Issue("error", f"{location}: expected number"))
    return issues


def load_schema_catalog() -> list[dict[str, Any]]:
    catalog = []
    for path in sorted(SCHEMA_DIR.glob("*.schema.yaml")):
        payload = load_yaml(path) or {}
        guard = payload.get("x-workflow-guard", {})
        catalog.append({"path": path, "schema": payload, "guard": guard})
    return catalog


def match_schema(path: Path, catalog: list[dict[str, Any]]) -> dict[str, Any] | None:
    path_text = rel(path)
    for entry in catalog:
        for pattern in entry["guard"].get("canonical_paths", []):
            if fnmatch.fnmatch(path_text, pattern):
                return entry
    return None


def iter_text_files(path: Path) -> list[Path]:
    if path.is_file():
        return [path]
    results: list[Path] = []
    for child in path.rglob("*"):
        if child.is_file() and child.suffix in {".md", ".yaml", ".json"}:
            results.append(child)
    return results


def validate_canonical_texts() -> list[Issue]:
    issues: list[Issue] = []
    for root in CANONICAL_TEXT_ROOTS:
        for path in iter_text_files(root):
            text = path.read_text()
            for token in FORBIDDEN_CANONICAL_TOKENS:
                if token in text:
                    issues.append(Issue("error", f"forbidden token `{token}` in canonical text", rel(path)))
    return issues


def validate_legacy_filenames() -> list[Issue]:
    issues: list[Issue] = []
    for pattern in LEGACY_FILE_PATTERNS:
        for path in ROOT.glob(pattern):
            if path.is_file():
                issues.append(Issue("error", "legacy filename/location is not allowed", rel(path)))
    return issues


def validate_creative_review_location() -> list[Issue]:
    issues: list[Issue] = []
    for path in ROOT.glob("project_data/projects/*/episodes/*/reviews/**/*.yaml"):
        payload = load_yaml(path) or {}
        stage = get_nested(payload, "metadata.target_stage")
        if stage == "creative":
            issues.append(Issue("error", "creative-stage reviews must live under project_data/projects/{project_id}/series/reviews", rel(path)))
    return issues


def validate_schema_key_paths(catalog: list[dict[str, Any]]) -> list[Issue]:
    issues: list[Issue] = []
    for entry in catalog:
        schema = entry["schema"]
        for dotted_path in entry["guard"].get("orchestrator_required_paths", []):
            if not path_exists_in_schema(schema, dotted_path):
                issues.append(
                    Issue(
                        "error",
                        f"schema missing orchestrator-required path `{dotted_path}`",
                        rel(entry["path"]),
                    )
                )
    return issues


def gather_based_on_paths(payload: Any) -> list[str]:
    based_on = get_nested(payload, "metadata.based_on")
    if not isinstance(based_on, dict):
        return []
    refs: list[str] = []
    for value in based_on.values():
        if isinstance(value, str) and value.endswith(".yaml"):
            refs.append(value)
        elif isinstance(value, list):
            refs.extend(item for item in value if isinstance(item, str) and item.endswith(".yaml"))
    return refs


def validate_based_on_references(catalog: list[dict[str, Any]]) -> list[Issue]:
    issues: list[Issue] = []
    for path in ROOT.glob("project_data/**/*.yaml"):
        if not path.is_file():
            continue
        entry = match_schema(path, catalog)
        if not entry:
            continue
        kind = entry["guard"].get("kind", "")
        if "review" in kind:
            continue
        payload = load_yaml(path) or {}
        for reference in gather_based_on_paths(payload):
            reference_path = (ROOT / reference).resolve()
            if not reference_path.exists():
                issues.append(Issue("error", f"missing based_on reference `{reference}`", rel(path)))
                continue
            upstream = load_yaml(reference_path) or {}
            status = get_nested(upstream, "metadata.status")
            if status != "approved":
                issues.append(
                    Issue(
                        "error",
                        f"downstream file references non-approved upstream `{reference}` (status={status!r})",
                        rel(path),
                    )
                )
    return issues


def validate_schema_files(catalog: list[dict[str, Any]]) -> list[Issue]:
    issues: list[Issue] = []
    for path in ROOT.glob("project_data/**/*.yaml"):
        if not path.is_file():
            continue
        entry = match_schema(path, catalog)
        if not entry:
            continue
        payload = load_yaml(path)
        issues.extend(
            Issue(issue.level, issue.message, rel(path)) for issue in validate_json_schema(payload, entry["schema"])
        )
    return issues


def find_formal_files() -> list[Path]:
    return sorted(path for path in ROOT.glob("project_data/**/*.yaml") if path.is_file())


def collect_validate_issues() -> list[Issue]:
    catalog = load_schema_catalog()
    issues: list[Issue] = []
    issues.extend(validate_canonical_texts())
    issues.extend(validate_legacy_filenames())
    issues.extend(validate_creative_review_location())
    issues.extend(validate_schema_key_paths(catalog))
    issues.extend(validate_schema_files(catalog))
    issues.extend(validate_based_on_references(catalog))
    return issues


def load_asset_segments(asset_index: dict[str, Any], asset_archive: dict[str, Any]) -> dict[str, str]:
    covered: dict[str, str] = {}
    for item in asset_index.get("segment_coverage", []) if isinstance(asset_index, dict) else []:
        segment_id = item.get("segment_id")
        if segment_id:
            covered[segment_id] = "approved" if item.get("is_complete") else "draft"
    archive_status = get_nested(asset_archive, "metadata.status")
    if archive_status == "approved":
        for segment_id in list(covered):
            covered[segment_id] = "approved"
    return covered


def load_video_segments(video_archive: dict[str, Any]) -> dict[str, str]:
    statuses: dict[str, str] = {}
    archive_status = get_nested(video_archive, "metadata.status")
    for result in video_archive.get("results", []) if isinstance(video_archive, dict) else []:
        segment_id = result.get("segment_id")
        if segment_id:
            statuses[segment_id] = archive_status or result.get("status", "draft")
    return statuses


def stage_status_from_file(payload: dict[str, Any] | None) -> str:
    if not payload:
        return "missing"
    return get_nested(payload, "metadata.status") or "missing"


def build_segment_ledger(project_id: str, episode_id: str) -> dict[str, Any]:
    segments_path = latest_formal_file(project_pattern(project_id, f"episodes/{episode_id}/segments/segments-v*.yaml"))
    segments_payload = load_yaml(segments_path) if segments_path else None
    segment_items = segments_payload.get("segments", []) if isinstance(segments_payload, dict) else []
    asset_index_path = latest_formal_file(project_pattern(project_id, f"episodes/{episode_id}/assets/asset-index-v*.yaml"))
    asset_archive_path = latest_formal_file(project_pattern(project_id, f"episodes/{episode_id}/assets/asset-archive-v*.yaml"))
    video_archive_path = latest_formal_file(project_pattern(project_id, f"episodes/{episode_id}/videos/video-archive-v*.yaml"))
    asset_index = load_yaml(asset_index_path) if asset_index_path else {}
    asset_archive = load_yaml(asset_archive_path) if asset_archive_path else {}
    video_archive = load_yaml(video_archive_path) if video_archive_path else {}

    planning_status = stage_status_from_file(segments_payload)
    asset_segments = load_asset_segments(asset_index or {}, asset_archive or {})
    video_segments = load_video_segments(video_archive or {})

    asset_pre = review_verdict(latest_review(project_id, "asset", "compliance", episode_id, phase="pre_generation"))
    asset_business = review_verdict(latest_review(project_id, "asset", "business", episode_id))
    asset_compliance = review_verdict(latest_review(project_id, "asset", "compliance", episode_id, phase="post_generation"))
    video_pre = review_verdict(latest_review(project_id, "video", "compliance", episode_id, phase="pre_generation"))
    video_business = review_verdict(latest_review(project_id, "video", "business", episode_id))
    video_compliance = review_verdict(latest_review(project_id, "video", "compliance", episode_id, phase="post_generation"))

    items = []
    for item in segment_items:
        segment_id = item.get("segment_id", "")
        asset_status = asset_segments.get(segment_id, "missing")
        video_status = video_segments.get(segment_id, "missing")
        blocked_by: list[str] = []
        can_start_asset = planning_status == "approved" and compliance_allows(asset_pre)
        if planning_status != "approved":
            blocked_by.append("planning_not_approved")
        if not compliance_allows(asset_pre):
            blocked_by.append("asset_precheck_missing")
            can_start_asset = False

        can_start_video = (
            planning_status == "approved"
            and asset_status == "approved"
            and business_allows(asset_business)
            and compliance_allows(asset_compliance)
            and compliance_allows(video_pre)
        )
        if asset_status != "approved":
            blocked_by.append("asset_output_not_approved")
        if not business_allows(asset_business):
            blocked_by.append("asset_business_not_allowed")
        if not compliance_allows(asset_compliance):
            blocked_by.append("asset_compliance_not_allowed")
        if not compliance_allows(video_pre):
            blocked_by.append("video_precheck_missing")

        items.append(
            {
                "segment_id": segment_id,
                "planning_status": planning_status,
                "asset_precheck_compliance": asset_pre,
                "asset_output_status": asset_status,
                "asset_business_verdict": asset_business,
                "asset_compliance_verdict": asset_compliance,
                "video_precheck_compliance": video_pre,
                "video_output_status": video_status,
                "video_business_verdict": video_business,
                "video_compliance_verdict": video_compliance,
                "blocked_by": sorted(set(blocked_by)),
                "can_start_asset": can_start_asset and asset_status != "approved",
                "can_start_video": can_start_video and video_status != "approved",
            }
        )

    return {"project_id": project_id, "episode_id": episode_id, "generated_at": "status-scan", "items": items}


def build_orchestration_result(project_id: str, episode_id: str) -> dict[str, Any]:
    creative_path = latest_formal_file(project_pattern(project_id, "series/creative-bible-v*.yaml"))
    script_path = latest_formal_file(project_pattern(project_id, f"episodes/{episode_id}/script/script-v*.yaml"))
    segments_path = latest_formal_file(project_pattern(project_id, f"episodes/{episode_id}/segments/segments-v*.yaml"))
    asset_manifest_path = latest_formal_file(project_pattern(project_id, f"episodes/{episode_id}/assets/asset-manifest-v*.yaml"))
    video_tasks_path = latest_formal_file(project_pattern(project_id, f"episodes/{episode_id}/videos/video-tasks-v*.yaml"))
    video_archive_path = latest_formal_file(project_pattern(project_id, f"episodes/{episode_id}/videos/video-archive-v*.yaml"))

    creative = load_yaml(creative_path) if creative_path else None
    script = load_yaml(script_path) if script_path else None
    segments = load_yaml(segments_path) if segments_path else None
    asset_manifest = load_yaml(asset_manifest_path) if asset_manifest_path else None
    video_tasks = load_yaml(video_tasks_path) if video_tasks_path else None
    video_archive = load_yaml(video_archive_path) if video_archive_path else None

    series_id = get_nested(creative, "metadata.series_id") or ""
    creative_business = latest_review(project_id, "creative", "business")
    creative_compliance = latest_review(project_id, "creative", "compliance")
    script_business = latest_review(project_id, "script", "business", episode_id)
    script_compliance = latest_review(project_id, "script", "compliance", episode_id)
    planning_business = latest_review(project_id, "planning", "business", episode_id)
    planning_compliance = latest_review(project_id, "planning", "compliance", episode_id)

    available_inputs = []
    for name, path, payload in (
        ("创意设定文件", creative_path, creative),
        ("单集剧本", script_path, script),
        ("segment 总表", segments_path, segments),
        ("资产清单", asset_manifest_path, asset_manifest),
        ("视频任务", video_tasks_path, video_tasks),
        ("视频归档", video_archive_path, video_archive),
    ):
        if path and payload:
            available_inputs.append(
                {
                    "name": name,
                    "path": rel(path),
                    "version": get_nested(payload, "metadata.version") or "",
                    "status": get_nested(payload, "metadata.status") or "missing",
                }
            )

    stage = "创意定义"
    stage_status = "未开始"
    detection_basis = "缺少正式创意设定文件"
    current_goal = "完成创意定义并形成可审核的创意设定"
    missing_deliverables: list[dict[str, Any]] = []
    missing_reviews: list[dict[str, Any]] = []
    next_agent = "creative-development-agent"
    next_skill = "creative-discovery-and-convergence"
    next_action = "继续完善创意设定"
    needs_business_review = False
    needs_compliance_review = False
    can_advance = False
    advance_reason = "创意阶段尚未完成"
    blockers: list[dict[str, str]] = []

    creative_status = stage_status_from_file(creative)
    script_status = stage_status_from_file(script)
    planning_status = stage_status_from_file(segments)

    creative_business_verdict = review_verdict(creative_business)
    creative_compliance_verdict = review_verdict(creative_compliance)
    script_business_verdict = review_verdict(script_business)
    script_compliance_verdict = review_verdict(script_compliance)
    planning_business_verdict = review_verdict(planning_business)
    planning_compliance_verdict = review_verdict(planning_compliance)

    if not creative or creative_status != "approved" or not business_allows(creative_business_verdict) or not compliance_allows(creative_compliance_verdict):
        stage = "创意定义"
        stage_status = {"draft": "进行中", "in_review": "审核中", "rejected": "已退回", "approved": "审核中"}.get(creative_status, "未开始")
        detection_basis = (
            f"{rel(creative_path)} status={creative_status}, "
            f"business={creative_business_verdict}, compliance={creative_compliance_verdict}"
            if creative_path
            else f"缺少 {project_pattern(project_id, 'series/creative-bible-v*.yaml')}"
        )
        if not creative_path:
            missing_deliverables.append({"name": "正式创意设定文件", "required_by": "剧本开发阶段", "priority": "critical"})
            blockers.append({"description": "缺少正式创意设定文件", "type": "missing_deliverable", "resolution": "继续创意定义"})
        if creative_path and not business_allows(creative_business_verdict):
            needs_business_review = True
            missing_reviews.append(
                {
                    "review_type": "business_review",
                    "target": rel(creative_path),
                    "phase": "stage_gate",
                    "required_before": "进入剧本开发",
                    "verdict": creative_business_verdict,
                }
            )
        if creative_path and not compliance_allows(creative_compliance_verdict):
            needs_compliance_review = True
            missing_reviews.append(
                {
                    "review_type": "compliance_review",
                    "target": rel(creative_path),
                    "phase": "stage_gate",
                    "required_before": "进入剧本开发",
                    "verdict": creative_compliance_verdict,
                }
            )
        if needs_business_review or needs_compliance_review:
            next_agent = "business-review-agent / compliance-review-agent"
            next_skill = ""
            next_action = "补齐创意阶段审核 verdict"
            current_goal = "完成创意阶段审核并获得放行 verdict"
            advance_reason = "创意阶段审核尚未放行"
        return {
            "timestamp": "status-scan",
            "project_id": project_id,
            "series_id": series_id,
            "episode_id": episode_id,
            "current_stage": stage,
            "stage_status": stage_status,
            "detection_basis": detection_basis,
            "current_goal": current_goal,
            "available_inputs": available_inputs,
            "missing_deliverables": missing_deliverables,
            "missing_reviews": missing_reviews,
            "next_agent": next_agent,
            "next_skill": next_skill,
            "next_action": next_action,
            "needs_business_review": needs_business_review,
            "needs_compliance_review": needs_compliance_review,
            "can_advance": can_advance,
            "advance_reason": advance_reason,
            "parallel_allowed": False,
            "parallel_tasks": [],
            "parallel_block_reason": "前三阶段严格串行",
            "blockers": blockers,
            "next_steps": [],
        }

    if not script or script_status != "approved" or not business_allows(script_business_verdict) or not compliance_allows(script_compliance_verdict):
        stage = "剧本开发"
        stage_status = {"draft": "进行中", "in_review": "审核中", "rejected": "已退回", "approved": "审核中"}.get(script_status, "未开始")
        detection_basis = (
            f"{rel(script_path)} status={script_status}, business={script_business_verdict}, compliance={script_compliance_verdict}"
            if script_path
            else f"{rel(creative_path)} 已放行，但缺少 script/script-v*.yaml"
        )
        current_goal = "完成当前集剧本并获得业务 / 合规放行"
        next_agent = "script-development-agent"
        next_skill = "market-oriented-script-development"
        next_action = "继续编写或修订单集剧本"
        if not script_path:
            missing_deliverables.append({"name": "单集剧本", "required_by": "生产规划阶段", "priority": "critical"})
        if script_path and not business_allows(script_business_verdict):
            needs_business_review = True
            missing_reviews.append(
                {
                    "review_type": "business_review",
                    "target": rel(script_path),
                    "phase": "stage_gate",
                    "required_before": "进入生产规划",
                    "verdict": script_business_verdict,
                }
            )
        if script_path and not compliance_allows(script_compliance_verdict):
            needs_compliance_review = True
            missing_reviews.append(
                {
                    "review_type": "compliance_review",
                    "target": rel(script_path),
                    "phase": "stage_gate",
                    "required_before": "进入生产规划",
                    "verdict": script_compliance_verdict,
                }
            )
        if needs_business_review or needs_compliance_review:
            next_agent = "business-review-agent / compliance-review-agent"
            next_skill = ""
            next_action = "补齐剧本阶段审核 verdict"
            advance_reason = "剧本阶段审核尚未放行"
        else:
            advance_reason = "剧本正式文件尚未 approved"
        return {
            "timestamp": "status-scan",
            "project_id": project_id,
            "series_id": series_id,
            "episode_id": episode_id,
            "current_stage": stage,
            "stage_status": stage_status,
            "detection_basis": detection_basis,
            "current_goal": current_goal,
            "available_inputs": available_inputs,
            "missing_deliverables": missing_deliverables,
            "missing_reviews": missing_reviews,
            "next_agent": next_agent,
            "next_skill": next_skill,
            "next_action": next_action,
            "needs_business_review": needs_business_review,
            "needs_compliance_review": needs_compliance_review,
            "can_advance": False,
            "advance_reason": advance_reason,
            "parallel_allowed": False,
            "parallel_tasks": [],
            "parallel_block_reason": "前三阶段严格串行",
            "blockers": blockers,
            "next_steps": [],
        }

    if not segments or planning_status != "approved" or not business_allows(planning_business_verdict) or not compliance_allows(planning_compliance_verdict):
        stage = "生产规划"
        stage_status = {"draft": "进行中", "in_review": "审核中", "rejected": "已退回", "approved": "审核中"}.get(planning_status, "未开始")
        detection_basis = (
            f"{rel(segments_path)} status={planning_status}, business={planning_business_verdict}, compliance={planning_compliance_verdict}"
            if segments_path
            else f"{rel(script_path)} 已放行，但缺少 segments/segments-v*.yaml"
        )
        current_goal = "完成 segment 总表和任务文件并获得审核放行"
        next_agent = "production-planning-agent"
        next_skill = "segment-planning-and-structuring"
        next_action = "继续完善 segment 规划"
        if not segments_path:
            missing_deliverables.append({"name": "segment 总表", "required_by": "资产生产阶段", "priority": "critical"})
        if segments_path and not business_allows(planning_business_verdict):
            needs_business_review = True
            missing_reviews.append(
                {
                    "review_type": "business_review",
                    "target": rel(segments_path),
                    "phase": "stage_gate",
                    "required_before": "进入资产生产",
                    "verdict": planning_business_verdict,
                }
            )
        if segments_path and not compliance_allows(planning_compliance_verdict):
            needs_compliance_review = True
            missing_reviews.append(
                {
                    "review_type": "compliance_review",
                    "target": rel(segments_path),
                    "phase": "stage_gate",
                    "required_before": "进入资产生产",
                    "verdict": planning_compliance_verdict,
                }
            )
        if needs_business_review or needs_compliance_review:
            next_agent = "business-review-agent / compliance-review-agent"
            next_skill = ""
            next_action = "补齐规划阶段审核 verdict"
            advance_reason = "规划阶段审核尚未放行"
        else:
            advance_reason = "segment 总表尚未 approved"
        return {
            "timestamp": "status-scan",
            "project_id": project_id,
            "series_id": series_id,
            "episode_id": episode_id,
            "current_stage": stage,
            "stage_status": stage_status,
            "detection_basis": detection_basis,
            "current_goal": current_goal,
            "available_inputs": available_inputs,
            "missing_deliverables": missing_deliverables,
            "missing_reviews": missing_reviews,
            "next_agent": next_agent,
            "next_skill": next_skill,
            "next_action": next_action,
            "needs_business_review": needs_business_review,
            "needs_compliance_review": needs_compliance_review,
            "can_advance": False,
            "advance_reason": advance_reason,
            "parallel_allowed": False,
            "parallel_tasks": [],
            "parallel_block_reason": "前三阶段严格串行",
            "blockers": blockers,
            "next_steps": [],
        }

    ledger = build_segment_ledger(project_id, episode_id)
    can_start_asset = [item["segment_id"] for item in ledger["items"] if item["can_start_asset"]]
    can_start_video = [item["segment_id"] for item in ledger["items"] if item["can_start_video"]]
    parallel_tasks = [f"{segment_id} 资产生产" for segment_id in can_start_asset] + [
        f"{segment_id} 视频生产" for segment_id in can_start_video
    ]

    if video_archive or can_start_video:
        stage = "视频生产"
        next_agent = "video-production-agent" if can_start_video else "business-review-agent / compliance-review-agent"
        next_skill = "video-generation-and-control" if can_start_video else ""
        next_action = "推进可启动 segment 的视频任务" if can_start_video else "补齐视频审核 verdict"
        stage_status = "进行中" if can_start_video else "审核中"
        current_goal = "推进可启动 segment 的视频任务，并等待剩余 segment 满足门禁"
        advance_reason = "仍有 segment 未完成视频放行"
        detection_basis = "segment 总表已 approved，至少一个 segment 可进入视频阶段"
    else:
        stage = "资产生产"
        next_agent = "asset-production-agent" if can_start_asset else "compliance-review-agent"
        next_skill = "asset-planning-and-prompting" if can_start_asset else ""
        next_action = "推进可启动 segment 的资产任务" if can_start_asset else "补齐资产前置合规 verdict"
        stage_status = "进行中" if can_start_asset else "审核中"
        current_goal = "推进可启动 segment 的资产任务，并补齐视频前置条件"
        advance_reason = "仍有 segment 未完成资产放行"
        detection_basis = "segment 总表已 approved，资产 / 视频阶段按 segment ledger 推进"

    return {
        "timestamp": "status-scan",
        "project_id": project_id,
        "series_id": series_id,
        "episode_id": episode_id,
        "current_stage": stage,
        "stage_status": stage_status,
        "detection_basis": detection_basis,
        "current_goal": current_goal,
        "available_inputs": available_inputs,
        "missing_deliverables": [],
        "missing_reviews": [],
        "next_agent": next_agent,
        "next_skill": next_skill,
        "next_action": next_action,
        "needs_business_review": False,
        "needs_compliance_review": False,
        "can_advance": False,
        "advance_reason": advance_reason,
        "parallel_allowed": bool(parallel_tasks),
        "parallel_tasks": parallel_tasks,
        "parallel_block_reason": "" if parallel_tasks else "当前没有满足门禁的 segment",
        "blockers": blockers,
        "next_steps": [],
    }


def project_ids_to_scan(selected_project: str | None) -> list[str]:
    if selected_project:
        return [selected_project]
    if not PROJECTS_ROOT.exists():
        return []
    return sorted(entry.name for entry in PROJECTS_ROOT.iterdir() if entry.is_dir() and not entry.name.startswith("."))


def episodes_to_scan(project_id: str, selected_episode: str | None) -> list[str]:
    if selected_episode:
        return [selected_episode]
    episodes_root = PROJECTS_ROOT / project_id / "episodes"
    if not episodes_root.exists():
        return ["epXX"]
    episodes = sorted(
        entry.name
        for entry in episodes_root.iterdir()
        if entry.is_dir() and not entry.name.startswith(".")
    )
    return episodes or ["epXX"]


def command_validate(_: argparse.Namespace) -> int:
    issues = collect_validate_issues()
    if issues:
        for issue in issues:
            prefix = issue.path or "workspace"
            print(f"[{issue.level}] {prefix}: {issue.message}")
        return 1
    print("validation passed")
    return 0


def command_status(args: argparse.Namespace) -> int:
    payload = {"projects": []}
    for project_id in project_ids_to_scan(args.project):
        project_payload = {"project_id": project_id, "episodes": []}
        for episode_id in episodes_to_scan(project_id, args.episode):
            orchestration = build_orchestration_result(project_id, episode_id)
            ledger = build_segment_ledger(project_id, episode_id)
            project_payload["episodes"].append({"orchestration_result": orchestration, "segment_ledger": ledger})
        payload["projects"].append(project_payload)
    print(dump_yaml(payload))
    return 0


def transform_to_compat(text: str) -> str:
    return text.replace("AGENTS.md", "CLAUDE.md").replace(".agents/", ".claude/")


def sync_tree(source_root: Path, target_root: Path) -> None:
    source_files = [path for path in source_root.rglob("*") if path.is_file()]
    source_rel = {path.relative_to(source_root) for path in source_files}
    if target_root.exists():
        for existing in sorted(path for path in target_root.rglob("*") if path.is_file()):
            if existing.relative_to(target_root) not in source_rel:
                existing.unlink()
    target_root.mkdir(parents=True, exist_ok=True)
    for source in source_files:
        relative = source.relative_to(source_root)
        target = target_root / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        if source.suffix == ".md":
            target.write_text(COMPAT_NOTICE + transform_to_compat(source.read_text()))
        elif source.suffix == ".json":
            data = json.loads(source.read_text())
            target.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n")
        else:
            shutil.copy2(source, target)


def command_sync_compat(_: argparse.Namespace) -> int:
    sync_tree(ROOT / ".agents" / "agents", ROOT / ".claude" / "agents")
    sync_tree(ROOT / ".agents" / "skills", ROOT / ".claude" / "skills")
    sync_tree(ROOT / ".agents", ROOT / ".claude")
    claude_md = ROOT / "CLAUDE.md"
    claude_md.write_text(COMPAT_NOTICE + transform_to_compat((ROOT / "AGENTS.md").read_text()))
    print("compat mirror synced")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Workflow guard for the AI 漫剧生产系统")
    subparsers = parser.add_subparsers(dest="command", required=True)

    validate_parser = subparsers.add_parser("validate", help="Validate canonical docs, schemas, and file layout")
    validate_parser.set_defaults(func=command_validate)

    status_parser = subparsers.add_parser("status", help="Read-only project status scan")
    status_parser.add_argument("--project", help="Only scan one project id, for example SER20260424-001")
    status_parser.add_argument("--episode", help="Only scan one episode id, for example ep01")
    status_parser.set_defaults(func=command_status)

    sync_parser = subparsers.add_parser("sync-compat", help="Generate compat mirrors under .claude/")
    sync_parser.set_defaults(func=command_sync_compat)
    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
