#!/usr/bin/env python3
from __future__ import annotations

import argparse
import fnmatch
import json
import re
import shutil
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tools" / "_vendor"))

import yaml


SCHEMA_DIR = ROOT / "schemas"
PROJECTS_ROOT = ROOT / "project_data" / "projects"
CANONICAL_TEXT_ROOTS = [ROOT / "AGENTS.md", ROOT / "README.md", ROOT / "docs", ROOT / ".agents"]
FORBIDDEN_CANONICAL_TOKENS = (".Codex", ".claude", "CLAUDE.md")
CODEX_GENERATED_IMAGE_TOKEN = "/.codex/generated_images/"
COMPAT_NOTICE = (
    "<!-- compat mirror: generated by tools/workflow_guard.py sync-compat. "
    "Do not edit this file directly. -->\n\n"
)


@dataclass
class Issue:
    level: str
    message: str
    path: str | None = None


V2_DELIVERABLES = [
    {
        "key": "creative_thesis",
        "name": "creative-thesis",
        "stage": "作品与剧本",
        "agent": "story-agent",
        "skill": "story-kill-rubric",
        "patterns": ["series/creative-thesis-v*.yaml"],
    },
    {
        "key": "script",
        "name": "script",
        "stage": "作品与剧本",
        "agent": "story-agent",
        "skill": "story-kill-rubric",
        "patterns": ["episodes/{episode_id}/script/script-v*.yaml"],
    },
    {
        "key": "script_doctor_report",
        "name": "script-doctor-report",
        "stage": "作品与剧本",
        "agent": "story-agent",
        "skill": "humanizer-pass",
        "patterns": ["episodes/{episode_id}/script/script-doctor-report-v*.yaml"],
    },
    {
        "key": "shot_design_table",
        "name": "shot-design-table",
        "stage": "导演设计",
        "agent": "director-agent",
        "skill": "director-shot-design",
        "patterns": ["episodes/{episode_id}/director/shot-design-table-v*.yaml"],
    },
    {
        "key": "visual_style_bible",
        "name": "visual-style-bible",
        "stage": "视觉资产",
        "agent": "visual-asset-agent",
        "skill": "visual-style-bible",
        "patterns": ["episodes/{episode_id}/assets/visual-style-bible-v*.yaml"],
    },
    {
        "key": "asset_index",
        "name": "asset-index",
        "stage": "视觉资产",
        "agent": "visual-asset-agent",
        "skill": "visual-style-bible",
        "patterns": ["episodes/{episode_id}/assets/asset-index-v*.yaml"],
    },
    {
        "key": "seedance_calibration_report",
        "name": "seedance-calibration-report",
        "stage": "Seedance 试拍校准",
        "agent": "seedance-package-agent",
        "skill": "seedance-calibration",
        "patterns": ["episodes/{episode_id}/seedance/seedance-calibration-report-v*.yaml"],
    },
    {
        "key": "generation_failure_library",
        "name": "generation-failure-library",
        "stage": "Seedance 试拍校准",
        "agent": "seedance-package-agent",
        "skill": "seedance-calibration",
        "patterns": ["episodes/{episode_id}/seedance/generation-failure-library-v*.yaml"],
    },
    {
        "key": "manual_generation_package",
        "name": "manual-generation-package",
        "stage": "Seedance 手工生成包",
        "agent": "seedance-package-agent",
        "skill": "seedance-upload-package",
        "patterns": ["episodes/{episode_id}/seedance/manual-generation-package-v*.yaml"],
    },
    {
        "key": "suno_music_task_card",
        "name": "suno-music-task-card",
        "stage": "音乐生成",
        "agent": "music-agent",
        "skill": "suno-music-generation",
        "patterns": ["episodes/{episode_id}/music/suno-music-task-card-v*.yaml"],
        "optional": True,
    },
]


def rel(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def load_yaml(path: Path) -> Any:
    text = path.read_text()
    return yaml.safe_load(text) if text.strip() else None


def dump_yaml(data: Any) -> str:
    return yaml.safe_dump(data, sort_keys=False, allow_unicode=True)


def parse_version(value: str) -> tuple[int, ...]:
    match = re.search(r"-v(\d+(?:\.\d+)*)", value)
    if not match:
        return (0,)
    return tuple(int(part) for part in match.group(1).split("."))


def latest_file(patterns: list[str]) -> Path | None:
    candidates: list[Path] = []
    for pattern in patterns:
        candidates.extend(ROOT.glob(pattern))
    files = [path for path in candidates if path.is_file()]
    if not files:
        return None
    files.sort(key=lambda path: (parse_version(path.name), path.name))
    return files[-1]


def project_pattern(project_id: str, relative_pattern: str) -> str:
    return f"project_data/projects/{project_id}/{relative_pattern}"


def get_nested(mapping: Any, dotted_path: str) -> Any:
    current = mapping
    for token in dotted_path.split("."):
        if not isinstance(current, dict) or token not in current:
            return None
        current = current[token]
    return current


def stage_status_from_file(payload: dict[str, Any] | None) -> str:
    if not payload:
        return "missing"
    return get_nested(payload, "metadata.status") or "missing"


def validate_json_schema(instance: Any, schema: dict[str, Any], location: str = "$") -> list[Issue]:
    issues: list[Issue] = []
    schema_type = schema.get("type")
    if "enum" in schema and instance not in schema["enum"]:
        issues.append(Issue("error", f"{location}: expected one of {schema['enum']}, got {instance!r}"))
        return issues
    if schema_type == "object":
        if not isinstance(instance, dict):
            issues.append(Issue("error", f"{location}: expected object"))
            return issues
        for key in schema.get("required", []):
            if key not in instance:
                issues.append(Issue("error", f"{location}: missing required key `{key}`"))
        props = schema.get("properties", {})
        if schema.get("additionalProperties") is False:
            for key in instance:
                if key not in props:
                    issues.append(Issue("error", f"{location}: unexpected key `{key}`"))
        for key, value in instance.items():
            if key in props:
                issues.extend(validate_json_schema(value, props[key], f"{location}.{key}"))
    elif schema_type == "array":
        if not isinstance(instance, list):
            issues.append(Issue("error", f"{location}: expected array"))
            return issues
        if "minItems" in schema and len(instance) < schema["minItems"]:
            issues.append(Issue("error", f"{location}: expected at least {schema['minItems']} items"))
        item_schema = schema.get("items")
        if item_schema:
            for index, item in enumerate(instance):
                issues.extend(validate_json_schema(item, item_schema, f"{location}[{index}]"))
    elif schema_type == "string":
        if not isinstance(instance, str):
            issues.append(Issue("error", f"{location}: expected string"))
    elif schema_type == "integer":
        if not isinstance(instance, int) or isinstance(instance, bool):
            issues.append(Issue("error", f"{location}: expected integer"))
    elif schema_type == "boolean":
        if not isinstance(instance, bool):
            issues.append(Issue("error", f"{location}: expected boolean"))
    elif schema_type == "number":
        if not isinstance(instance, (int, float)) or isinstance(instance, bool):
            issues.append(Issue("error", f"{location}: expected number"))
    return issues


def load_schema_catalog() -> list[dict[str, Any]]:
    catalog = []
    for path in sorted(SCHEMA_DIR.glob("*.schema.yaml")):
        payload = load_yaml(path) or {}
        catalog.append({"path": path, "schema": payload, "guard": payload.get("x-workflow-guard", {})})
    return catalog


def match_schema(path: Path, catalog: list[dict[str, Any]]) -> dict[str, Any] | None:
    path_text = rel(path)
    for entry in catalog:
        for pattern in entry["guard"].get("canonical_paths", []):
            if fnmatch.fnmatch(path_text, pattern):
                return entry
    return None


def iter_text_files(path: Path) -> list[Path]:
    if path.is_file():
        return [path]
    if not path.exists():
        return []
    return sorted(child for child in path.rglob("*") if child.is_file() and child.suffix in {".md", ".yaml", ".json"})


def validate_canonical_texts() -> list[Issue]:
    issues: list[Issue] = []
    for root in CANONICAL_TEXT_ROOTS:
        for path in iter_text_files(root):
            text = path.read_text()
            for token in FORBIDDEN_CANONICAL_TOKENS:
                if token in text:
                    issues.append(Issue("error", f"forbidden token `{token}` in canonical text", rel(path)))
    return issues


def iter_scalar_strings(node: Any, path_parts: list[str] | None = None) -> list[tuple[list[str], str]]:
    path_parts = path_parts or []
    values: list[tuple[list[str], str]] = []
    if isinstance(node, dict):
        for key, value in node.items():
            values.extend(iter_scalar_strings(value, path_parts + [str(key)]))
    elif isinstance(node, list):
        for index, value in enumerate(node):
            values.extend(iter_scalar_strings(value, path_parts + [f"[{index}]"]))
    elif isinstance(node, str):
        values.append((path_parts, node))
    return values


def validate_formal_paths() -> list[Issue]:
    issues: list[Issue] = []
    for path in ROOT.glob("project_data/**/*.yaml"):
        if not path.is_file():
            continue
        payload = load_yaml(path)
        for _, value in iter_scalar_strings(payload):
            if CODEX_GENERATED_IMAGE_TOKEN in value:
                issues.append(Issue("error", "formal files must not reference Codex generated image staging paths", rel(path)))
    return issues


def validate_schema_files(catalog: list[dict[str, Any]]) -> list[Issue]:
    issues: list[Issue] = []
    for path in ROOT.glob("project_data/**/*.yaml"):
        if not path.is_file():
            continue
        entry = match_schema(path, catalog)
        if not entry:
            continue
        payload = load_yaml(path)
        issues.extend(Issue(issue.level, issue.message, rel(path)) for issue in validate_json_schema(payload, entry["schema"]))
    return issues


def validate_manual_generation_packages() -> list[Issue]:
    issues: list[Issue] = []
    for path in ROOT.glob("project_data/projects/*/episodes/*/seedance/manual-generation-package-v*.yaml"):
        payload = load_yaml(path) or {}
        for index, task in enumerate(payload.get("tasks", [])):
            manifest = task.get("platform_upload_manifest", [])
            if len(manifest) > 9:
                issues.append(Issue("error", f"tasks[{index}] upload manifest has {len(manifest)} images; Seedance limit is 9", rel(path)))
            audio = task.get("audio", {})
            if audio.get("dialogue_present") and not str(audio.get("prompt_text", "")).strip():
                issues.append(Issue("error", f"tasks[{index}] dialogue task must include audio.prompt_text", rel(path)))
            if audio.get("dialogue_present") and "Audio:" not in str(audio.get("prompt_text", "")):
                issues.append(Issue("error", f"tasks[{index}] dialogue task audio.prompt_text must include `Audio:`", rel(path)))
    return issues


def collect_validate_issues() -> list[Issue]:
    catalog = load_schema_catalog()
    issues: list[Issue] = []
    issues.extend(validate_canonical_texts())
    issues.extend(validate_schema_files(catalog))
    issues.extend(validate_formal_paths())
    issues.extend(validate_manual_generation_packages())
    return issues


def project_ids_to_scan(project_arg: str | None) -> list[str]:
    if project_arg:
        return [project_arg]
    if not PROJECTS_ROOT.exists():
        return []
    return sorted(entry.name for entry in PROJECTS_ROOT.iterdir() if entry.is_dir() and not entry.name.startswith("."))


def episodes_to_scan(project_id: str, episode_arg: str | None) -> list[str]:
    if episode_arg:
        return [episode_arg]
    episodes_root = PROJECTS_ROOT / project_id / "episodes"
    if not episodes_root.exists():
        return ["ep01"]
    episodes = sorted(entry.name for entry in episodes_root.iterdir() if entry.is_dir() and not entry.name.startswith("."))
    return episodes or ["ep01"]


def deliverable_path(project_id: str, episode_id: str, spec: dict[str, Any]) -> Path | None:
    patterns = [project_pattern(project_id, pattern.format(episode_id=episode_id)) for pattern in spec["patterns"]]
    return latest_file(patterns)


def deliverable_status(project_id: str, episode_id: str) -> dict[str, dict[str, Any]]:
    statuses: dict[str, dict[str, Any]] = {}
    for spec in V2_DELIVERABLES:
        path = deliverable_path(project_id, episode_id, spec)
        payload = load_yaml(path) if path else None
        statuses[spec["key"]] = {
            "name": spec["name"],
            "path": rel(path) if path else "",
            "status": stage_status_from_file(payload),
            "optional": bool(spec.get("optional")),
            "agent": spec["agent"],
            "skill": spec["skill"],
            "stage": spec["stage"],
        }
    return statuses


def build_studio_status(project_id: str, episode_id: str) -> dict[str, Any]:
    statuses = deliverable_status(project_id, episode_id)
    missing_required = [
        item for item in statuses.values() if item["status"] != "approved" and not item["optional"]
    ]
    if missing_required:
        next_item = missing_required[0]
        current_stage = next_item["stage"]
        next_agent = next_item["agent"]
        next_skill = next_item["skill"]
        next_action = f"完成并 approved `{next_item['name']}`"
    else:
        current_stage = "手工生产就绪"
        next_agent = "seedance-package-agent"
        next_skill = "seedance-upload-package"
        next_action = "按 manual-generation-package 手工上传生成"

    return {
        "project_id": project_id,
        "episode_id": episode_id,
        "current_stage": current_stage,
        "can_start_seedance_batch": statuses["manual_generation_package"]["status"] == "approved",
        "missing_deliverables": [
            {"name": item["name"], "stage": item["stage"], "status": item["status"]}
            for item in missing_required
        ],
        "available_deliverables": [
            {"name": item["name"], "path": item["path"], "status": item["status"]}
            for item in statuses.values()
            if item["path"]
        ],
        "next_agent": next_agent,
        "next_skill": next_skill,
        "next_action": next_action,
    }


def load_latest_manual_package(project_id: str, episode_id: str) -> dict[str, Any] | None:
    path = deliverable_path(project_id, episode_id, next(item for item in V2_DELIVERABLES if item["key"] == "manual_generation_package"))
    return load_yaml(path) if path else None


def load_latest_shot_table(project_id: str, episode_id: str) -> dict[str, Any] | None:
    path = deliverable_path(project_id, episode_id, next(item for item in V2_DELIVERABLES if item["key"] == "shot_design_table"))
    return load_yaml(path) if path else None


def upload_path_exists(path_text: str) -> bool:
    if not path_text:
        return False
    path = Path(path_text)
    if not path.is_absolute():
        path = ROOT / path
    return path.exists()


def build_shot_ledger(project_id: str, episode_id: str) -> dict[str, Any]:
    shot_table = load_latest_shot_table(project_id, episode_id) or {}
    package = load_latest_manual_package(project_id, episode_id) or {}
    package_by_shot = {task.get("shot_id"): task for task in package.get("tasks", []) if isinstance(task, dict)}
    items = []
    for shot in shot_table.get("shots", []) if isinstance(shot_table, dict) else []:
        shot_id = shot.get("shot_id", "")
        task = package_by_shot.get(shot_id, {})
        upload_manifest = task.get("platform_upload_manifest", []) if isinstance(task, dict) else []
        audio = task.get("audio", {}) if isinstance(task, dict) else {}
        missing_required_upload_assets = []
        missing_optional_upload_assets = []
        for upload in upload_manifest:
            if not isinstance(upload, dict):
                continue
            path_text = str(upload.get("path", ""))
            if upload_path_exists(path_text):
                continue
            missing_item = {
                "asset_id": upload.get("asset_id", ""),
                "path": path_text,
            }
            if upload.get("required", True):
                missing_required_upload_assets.append(missing_item)
            else:
                missing_optional_upload_assets.append(missing_item)
        upload_required_assets_exist = bool(upload_manifest) and not missing_required_upload_assets
        audio_ok = not audio.get("dialogue_present") or bool(str(audio.get("prompt_text", "")).strip())
        items.append(
            {
                "shot_id": shot_id,
                "shot_status": shot.get("status", "draft"),
                "has_seedance_task": bool(task),
                "upload_count": len(upload_manifest),
                "upload_limit_ok": len(upload_manifest) <= 9,
                "upload_required_assets_exist": upload_required_assets_exist,
                "missing_required_upload_assets": missing_required_upload_assets,
                "missing_optional_upload_assets": missing_optional_upload_assets,
                "dialogue_present": bool(audio.get("dialogue_present")),
                "has_audio_prompt": bool(str(audio.get("prompt_text", "")).strip()),
                "ready_for_manual_generation": bool(task) and len(upload_manifest) <= 9 and upload_required_assets_exist and audio_ok,
            }
        )
    return {
        "project_id": project_id,
        "episode_id": episode_id,
        "generated_at": "status-scan",
        "items": items,
    }


def command_validate(_: argparse.Namespace) -> int:
    issues = collect_validate_issues()
    if issues:
        for issue in issues:
            prefix = issue.path or "workspace"
            print(f"[{issue.level}] {prefix}: {issue.message}")
        return 1
    print("validation passed")
    return 0


def command_status(args: argparse.Namespace) -> int:
    payload = {"projects": []}
    for project_id in project_ids_to_scan(args.project):
        project_payload = {"project_id": project_id, "episodes": []}
        for episode_id in episodes_to_scan(project_id, args.episode):
            project_payload["episodes"].append(
                {
                    "episode_id": episode_id,
                    "studio_status": build_studio_status(project_id, episode_id),
                    "shot_ledger": build_shot_ledger(project_id, episode_id),
                }
            )
        payload["projects"].append(project_payload)
    print(dump_yaml(payload))
    return 0


def transform_to_compat(text: str) -> str:
    return text.replace("AGENTS.md", "CLAUDE.md").replace(".agents/", ".claude/")


def sync_tree(source_root: Path, target_root: Path) -> None:
    source_files = [path for path in source_root.rglob("*") if path.is_file()]
    source_rel = {path.relative_to(source_root) for path in source_files}
    if target_root.exists():
        for existing in sorted(path for path in target_root.rglob("*") if path.is_file()):
            if existing.relative_to(target_root) not in source_rel:
                existing.unlink()
    target_root.mkdir(parents=True, exist_ok=True)
    for source in source_files:
        relative = source.relative_to(source_root)
        target = target_root / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        if source.suffix == ".md":
            target.write_text(COMPAT_NOTICE + transform_to_compat(source.read_text()))
        elif source.suffix == ".json":
            data = json.loads(source.read_text())
            target.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n")
        else:
            shutil.copy2(source, target)


def command_sync_compat(_: argparse.Namespace) -> int:
    sync_tree(ROOT / ".agents", ROOT / ".claude")
    claude_md = ROOT / "CLAUDE.md"
    claude_md.write_text(COMPAT_NOTICE + transform_to_compat((ROOT / "AGENTS.md").read_text()))
    print("compat mirror synced")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Workflow guard for the V2 AI 影像生产系统")
    subparsers = parser.add_subparsers(dest="command", required=True)

    validate_parser = subparsers.add_parser("validate", help="Validate formal project files and canonical docs")
    validate_parser.set_defaults(func=command_validate)

    status_parser = subparsers.add_parser("status", help="Report V2 studio status")
    status_parser.add_argument("--project", help="Project id to scan")
    status_parser.add_argument("--episode", help="Episode id to scan")
    status_parser.set_defaults(func=command_status)

    sync_parser = subparsers.add_parser("sync-compat", help="Generate compat mirrors")
    sync_parser.set_defaults(func=command_sync_compat)
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
